desc "Execute a lane using different environment variables"
desc "#### Options"
desc "* __**target_lane**__: The target lane to execute with different environment"
desc "  * **environment_variable**: TARGET_LANE"
desc "  * **type**: string"
desc "  * **optional**: false"
desc "#### Environment variables"
desc "* __**ENVIRONMENT_DIRECTORY_PATH**__: The directory path of the environment info"
desc "  * **type**: string"
desc "  * **optional**: true"
desc ""
lane :multi_environment do |options|
  prepare_lane_options(
    options: options,
    bind_params: [
      Actions::BindParamBuilder.new(:target_lane).env_var("TARGET_LANE").required.build()
    ]
  )
  target_lane = options[:target_lane]
  options.delete(:target_lane)
  initial_env = {}
  ENV.each { |k, v|
    initial_env[k] = v
  }
  env_hash = {}
  if envs = get_environments()
    envs.each { |name, env_path|
      if data = File.read(env_path)
        override = {}
        if lines = data.split("\n")
          lines.each { |line|
            if index = line.index('=')
              override[line[0..index-1]] = line[index+1..line.length]
            end
          }
        end
        env_hash[name] = override
      end
    }
  end
  if env_hash.length > 0
    env_hash.each { |name, envs|
      envs.each { |k, v|
        ENV[k] = v
      }
      ENV["ENVIRONMENT_NAME"] = name
      send(target_lane, options)
      ENV.clear()
      initial_env.each { |k, v|
        ENV[k] = v
      }
    }
  else
    send(target_lane, options)
  end
end
